name: Inputs test

on:
  push:
  workflow_dispatch:
    inputs:
      boolean:
        type: boolean
        description: boolean test
        default: true
        required: true

jobs:
  run_on_true:
    runs-on: ubuntu-latest
    if: ${{ inputs.boolean == true }}
    steps:
      - name: debug
        run: echo "input is set to ${{ inputs.boolean }}"

  run_on_false:
    runs-on: ubuntu-latest
    if: ${{ inputs.boolean != null && inputs.boolean == false }}
    steps:
      - name: debug
        run: echo "input is set to ${{ inputs.boolean }}"
